# Generated by Django 4.2.13 on 2024-07-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='competition',
            field=models.CharField(choices=[('cc1', 'County Champ Div 1'), ('cc2', 'County Champ Div 2'), ('t20', 'T20 Blast'), ('oneday', 'One Day Cup'), ('other', 'Other')], default='County Champ Div 1', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='stadium',
            field=models.CharField(choices=[('racecourse', 'Racecourse Ground (Derbyshire)'), ('riverside', 'Riverside (Durham)'), ('chelmsford', 'Chelmsford (Essex)'), ('sophia gardens', 'Sophia Gardens (Glamorgan)'), ('nevil road', 'Nevil Road (Gloucestershire)'), ('ageas bowl', 'Ageas Bowl (Hampshire)'), ('canterbury', 'Canterbury (Kent)'), ('old trafford', 'Old Trafford (Lancashire)'), ('grace road', 'Grace Road (Leicestershire)'), ('lords', 'Lords (Middlesex)'), ('northampton', 'Northampton (Northamptonsire)'), ('trent bridge', 'Trent Bridge (Nottinghamshire)'), ('taunton', 'Taunton (Somerset)'), ('oval', 'The Oval (Surrey)'), ('hove', 'Hove (Sussex)'), ('edgbaston', 'Edgbaston (Warwickshire)'), ('new road', 'New Road (Worcestershire)'), ('headingley', 'Headingley (Yorkshire)')], default='Lords', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='visitor',
            field=models.CharField(choices=[('derbyshire', 'Derbyshire'), ('durham', 'Durham'), ('essex', 'Essex'), ('glamorgan', 'Glamorgan'), ('gloucestershire', 'Gloucestershire'), ('hampshire', 'Hampshire'), ('kent', 'Kent'), ('lancashire', 'Lancashire'), ('leicestershire', 'Leicestershire'), ('middlesex', 'Middlesex'), ('northamptonshire', 'Northamptonshire'), ('nottinghamshire', 'Nottinghamshire'), ('somerset', 'Somerset'), ('surrey', 'Surrey'), ('sussex', 'Sussex'), ('warwickshire', 'Warwickshire'), ('worcestershire', 'Worcestershire'), ('yorkshire', 'Yorkshire')], default='Surrey', max_length=50),
        ),
    ]
