# Generated by Django 4.2.13 on 2024-07-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_on',
            new_name='added_on',
        ),
    ]
