# Generated by Django 4.2.13 on 2024-07-12 22:15

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_created_on_comment_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='competition',
            field=models.CharField(choices=[('County Champ Div 1', 'County Champ Div 1'), ('County Champ Div 2', 'County Champ Div 2'), ('T20 Blast', 'T20 Blast'), ('One Day Cup', 'One Day Cup'), ('Other', 'Other')], default='County Champ Div 1', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='stadium',
            field=models.CharField(choices=[('Racecourse Ground (Derbyshire)', 'Racecourse Ground (Derbyshire)'), ('Riverside (Durham)', 'Riverside (Durham)'), ('Chelmsford (Essex)', 'Chelmsford (Essex)'), ('Sophia Gardens (Glamorgan)', 'Sophia Gardens (Glamorgan)'), ('Nevil Road (Gloucestershire)', 'Nevil Road (Gloucestershire)'), ('Ageas Bowl (Hampshire)', 'Ageas Bowl (Hampshire)'), ('Canterbury (Kent)', 'Canterbury (Kent)'), ('Old Trafford (Lancashire)', 'Old Trafford (Lancashire)'), ('Grace Road (Leicestershire)', 'Grace Road (Leicestershire)'), ('Lords (Middlesex)', 'Lords (Middlesex)'), ('Northampton (Northamptonsire)', 'Northampton (Northamptonsire)'), ('Trent Bridge (Nottinghamshire)', 'Trent Bridge (Nottinghamshire)'), ('Taunton (Somerset)', 'Taunton (Somerset)'), ('The Oval (Surrey)', 'The Oval (Surrey)'), ('Hove (Sussex)', 'Hove (Sussex)'), ('Edgbaston (Warwickshire)', 'Edgbaston (Warwickshire)'), ('New Road (Worcestershire)', 'New Road (Worcestershire)'), ('Headingley (Yorkshire)', 'Headingley (Yorkshire)')], default='Lords', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='visitor',
            field=models.CharField(choices=[('Derbyshire', 'Derbyshire'), ('Durham', 'Durham'), ('Essex', 'Essex'), ('Glamorgan', 'Glamorgan'), ('Gloucestershire', 'Gloucestershire'), ('Hampshire', 'Hampshire'), ('Kent', 'Kent'), ('Lancashire', 'Lancashire'), ('Leicestershire', 'Leicestershire'), ('Middlesex', 'Middlesex'), ('Northamptonshire', 'Northamptonshire'), ('Nottinghamshire', 'Nottinghamshire'), ('Somerset', 'Somerset'), ('Surrey', 'Surrey'), ('Sussex', 'Sussex'), ('Warwickshire', 'Warwickshire'), ('Worcestershire', 'Worcestershire'), ('Yorkshire', 'Yorkshire')], default='Surrey', max_length=50),
        ),
    ]
